### ISSUE TITLE
Out of bounds memory read in function htmlGetText on malformed input

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/htmldoc#285]
Version: -current
Original reporter: Hanno Boeck

The attached file causes an out of bounds heap read access in the function htmlGetText. This was found with the tool american fuzzy lop and address sanitizer.

Address Sanitizer stack trace:
==13164==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000057d1 at pc 0x00000046461c bp 0x7fff1df26e90 sp 0x7fff1df26640
READ of size 2 at 0x6020000057d1 thread T0
    #0 0x46461b in strlen (/old-ram11/htmldoc/htmldoc-svn+0x46461b)
    #1 0x53d4a9 in htmlGetText /f/htmldoc/trunk/htmldoc/htmllib.cxx:1201:14
    #2 0x5206ff in get_title(hdTree*) /f/htmldoc/trunk/htmldoc/html.cxx:460:15
    #3 0x52065b in get_title(hdTree*) /f/htmldoc/trunk/htmldoc/html.cxx:462:19
    #4 0x51c9c6 in do_export(hdTree*, hdTree*, hdTree*, bool) /f/htmldoc/trunk/htmldoc/html.cxx:320:15
    #5 0x51c078 in html_export /f/htmldoc/trunk/htmldoc/html.cxx:111:11
    #6 0x50018f in main /f/htmldoc/trunk/htmldoc/htmldoc.cxx:1259:3
    #7 0x7f145e03d78f in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.23-r2/work/glibc-2.23/csu/../csu/libc-start.c:289
    #8 0x41a6e8 in _start (/old-ram11/htmldoc/htmldoc-svn+0x41a6e8)

0x6020000057d1 is located 0 bytes to the right of 1-byte region [0x6020000057d0,0x6020000057d1)
allocated by thread T0 here:
    #0 0x4c2558 in __interceptor_malloc (/old-ram11/htmldoc/htmldoc-svn+0x4c2558)
    #1 0x53d533 in htmlGetText /f/htmldoc/trunk/htmldoc/htmllib.cxx:1206:24

SUMMARY: AddressSanitizer: heap-buffer-overflow (/old-ram11/htmldoc/htmldoc-svn+0x46461b) in strlen
Shadow bytes around the buggy address:
  0x0c047fff8aa0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8ab0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8ac0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8ad0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8ae0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fff8af0: fa fa fa fa fa fa fa fa fa fa[01]fa fa fa 06 fa
  0x0c047fff8b00: fa fa 00 fa fa fa fd fa fa fa 00 05 fa fa 07 fa
  0x0c047fff8b10: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff8b20: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff8b30: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fd
  0x0c047fff8b40: fa fa fd fa fa fa 07 fa fa fa 06 fa fa fa 00 04
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb

**Comment by michaelrsweet** [comment]
This code is no longer in use.
