### ISSUE TITLE
Out of bounds heap read in function write_node

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/htmldoc#287]
Version: -current
Original reporter: Hanno Boeck

The attached file will cause an out of bounds heap read in the function write_node. This was found with the tool american fuzzy lop and address sanitizer.

Address Sanitizer stack trace:
==13168==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000660f at pc 0x00000052729e bp 0x7ffdb8604470 sp 0x7ffdb8604468
READ of size 1 at 0x60200000660f thread T0
    #0 0x52729d in write_node(hdFile*, hdTree*, int) /f/htmldoc/trunk/htmldoc/html.cxx:1181:8
    #1 0x52574b in write_all(hdFile*, hdTree*, int) /f/htmldoc/trunk/htmldoc/html.cxx:616:11
    #2 0x5257b9 in write_all(hdFile*, hdTree*, int) /f/htmldoc/trunk/htmldoc/html.cxx:619:13
    #3 0x51d4fd in do_export(hdTree*, hdTree*, hdTree*, bool) /f/htmldoc/trunk/htmldoc/html.cxx:368:7
    #4 0x51c078 in html_export /f/htmldoc/trunk/htmldoc/html.cxx:111:11
    #5 0x50018f in main /f/htmldoc/trunk/htmldoc/htmldoc.cxx:1259:3
    #6 0x7f7e55a4478f in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.23-r2/work/glibc-2.23/csu/../csu/libc-start.c:289
    #7 0x41a6e8 in _start (/old-ram11/htmldoc/htmldoc-svn+0x41a6e8)

0x60200000660f is located 1 bytes to the left of 1-byte region [0x602000006610,0x602000006611)
allocated by thread T0 here:
    #0 0x472e20 in strdup (/old-ram11/htmldoc/htmldoc-svn+0x472e20)
    #1 0x529437 in htmlReadFile /f/htmldoc/trunk/htmldoc/htmllib.cxx:563:29
    #2 0x5056d0 in read_file(char const*, hdTree**, char const*) /f/htmldoc/trunk/htmldoc/htmldoc.cxx:2455:5
    #3 0x4fb2bb in main /f/htmldoc/trunk/htmldoc/htmldoc.cxx:1171:7
    #4 0x7f7e55a4478f in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.23-r2/work/glibc-2.23/csu/../csu/libc-start.c:289

SUMMARY: AddressSanitizer: heap-buffer-overflow /f/htmldoc/trunk/htmldoc/html.cxx:1181:8 in write_node(hdFile*, hdTree*, int)
Shadow bytes around the buggy address:
  0x0c047fff8c70: fa fa 04 fa fa fa 05 fa fa fa 06 fa fa fa 04 fa
  0x0c047fff8c80: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 03 fa
  0x0c047fff8c90: fa fa 03 fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff8ca0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff8cb0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
=>0x0c047fff8cc0: fa[fa]01 fa fa fa 06 fa fa fa 00 05 fa fa 00 03
  0x0c047fff8cd0: fa fa 00 04 fa fa 00 04 fa fa fd fa fa fa 00 fa
  0x0c047fff8ce0: fa fa 00 fa fa fa fd fa fa fa 00 fa fa fa fd fa
  0x0c047fff8cf0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff8d00: fa fa fd fa fa fa 00 05 fa fa fd fa fa fa fd fa
  0x0c047fff8d10: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==13168==ABORTING

**Comment by michaelrsweet** [comment]
This code is no longer in use.
